module_order:
    - fastqc:
        name: 'FastQC (raw)'
        path_filters:
            - '*_fastqc.zip'
    - bbmap
    - fastqc:
        name: 'FastQC (trimmed)'
        info: 'This section of the report shows FastQC results after adapter trimming.'
        target: ''
        path_filters:
            - '*_trimmed_fastqc.zip'
    - bowtie2
    - picard
    - qualimap
    - featureCounts
